post http://127.0.0.1:4000/admin-auth/register
Content-Type: application/json

{
    "username": "bakii",
    "first_name": "bereket",
    "last_name": "zeselassie",
    "password": "    ",
    "company_name": "3T",
    "company_type": "restaurant",
    "admin_level": "superadmin",
    "reset_token": ""
}
###

post http://127.0.0.1:4000/admin-auth/login
Content-Type: application/json

{
    "username": "jack",
    "password": "    "
}

###
post http://127.0.0.1:4000/admin-auth/login
Content-Type: application/json

{
    "username": "fila",
    "password": "    "
}

###
post http://127.0.0.1:4000/admin-auth/logout

###
post http://127.0.0.1:4000/admin/reset-token
Content-Type: application/json

{
    "username": "bakii"
}

###
put http://127.0.0.1:4000/admin/password
Content-Type: application/json

{
    "reset_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJha2lpIiwiaWF0IjoxNzUxNDU3NDM3fQ.i0L9jeCUxXn0cviqdrZqDaE2VO_ankxXQWYpro63Qxw",
    "password": "    "
}

###

get http://127.0.0.1:4000/admin/profile

###

put http://127.0.0.1:4000/admin/meal/a838ffcb-dc2e-4403-bfc8-158512227293
Content-Type: application/json

{
    "title" : "Birthday Cake"
}

###
get http://127.0.0.1:4000/admin/all-image


///meal

###
post http://127.0.0.1:4000/admin/meal
Content-Type: application/json

{
    "created_by_id": "6c798719-7127-47ca-80c1-485868ac4179",
    "title": "Chocolate Cake",
    "is_available": true,
    "updated_by_id": "6c798719-7127-47ca-80c1-485868ac4179"    
}

###
put http://127.0.0.1:4000/admin/meal/e926ad95-8227-4073-a268-2e52ae379947
Content-Type: application/json

{
    "image": ""
}

###

put http://127.0.0.1:4000/admin/upload
Content-Type: application/json

{
    "parent_id": "a838ffcb-dc2e-4403-bfc8-158512227293",
    "parent_name": "image",
    "file_type": "image",
    "file_id": "89827217-346b-4e74-a4f1-157d1cd87b46"
}































